import { formatKes } from './currency';
import type { Invoice } from '../types';

function escapeHtml(value: string): string {
    return value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

/**
 * Build a standalone, printable HTML document for an invoice.
 */
export function buildInvoiceHtml(invoice: Invoice): string {
    const ref = invoice.id.slice(0, 8).toUpperCase();
    const date = new Date(invoice.created_at).toLocaleDateString('en-GB', {
        day: 'numeric', month: 'long', year: 'numeric',
    });
    const patientName = escapeHtml(invoice.patient?.name || 'Patient');
    const doctorName = escapeHtml(invoice.doctor?.name || 'Provider');
    const specialization = invoice.doctor?.specialization
        ? escapeHtml(invoice.doctor.specialization)
        : '';
    const description = escapeHtml(invoice.description || 'Consultation');
    const amount = formatKes(invoice.amount);
    const isPaid = invoice.status === 'paid';

    return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Invoice ${ref}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #1f2937; margin: 0; padding: 48px; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #2563eb; padding-bottom: 24px; }
  .brand { font-size: 24px; font-weight: 800; color: #2563eb; }
  .brand small { display: block; font-size: 11px; font-weight: 600; color: #9ca3af; letter-spacing: 2px; text-transform: uppercase; }
  .doc-title { text-align: right; }
  .doc-title h1 { margin: 0; font-size: 28px; letter-spacing: 4px; }
  .meta { color: #6b7280; font-size: 13px; margin-top: 4px; }
  .parties { display: flex; justify-content: space-between; margin: 32px 0; gap: 24px; }
  .parties h3 { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #9ca3af; margin: 0 0 6px; }
  .parties p { margin: 0; font-weight: 600; }
  .parties span { font-weight: 400; color: #6b7280; font-size: 13px; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #9ca3af; border-bottom: 1px solid #e5e7eb; padding: 8px 0; }
  td { padding: 14px 0; border-bottom: 1px solid #f3f4f6; }
  td.amt, th.amt { text-align: right; }
  .total { display: flex; justify-content: flex-end; margin-top: 24px; }
  .total-box { min-width: 240px; }
  .total-row { display: flex; justify-content: space-between; padding: 8px 0; }
  .total-row.grand { border-top: 2px solid #1f2937; font-size: 18px; font-weight: 800; margin-top: 4px; padding-top: 12px; }
  .status { display: inline-block; padding: 4px 12px; border-radius: 999px; font-size: 12px; font-weight: 700; }
  .status.paid { background: #ecfdf5; color: #047857; }
  .status.unpaid { background: #fffbeb; color: #b45309; }
  .foot { margin-top: 48px; text-align: center; color: #9ca3af; font-size: 12px; }
  @media print { body { padding: 24px; } .noprint { display: none; } }
</style>
</head>
<body>
  <div class="head">
    <div class="brand">🏥 Telehealth<small>Resource Management</small></div>
    <div class="doc-title">
      <h1>INVOICE</h1>
      <div class="meta">Ref: ${ref}</div>
      <div class="meta">Date: ${date}</div>
      <div class="meta"><span class="status ${isPaid ? 'paid' : 'unpaid'}">${isPaid ? 'PAID' : 'UNPAID'}</span></div>
    </div>
  </div>

  <div class="parties">
    <div>
      <h3>Billed To</h3>
      <p>${patientName}</p>
    </div>
    <div style="text-align:right">
      <h3>Provider</h3>
      <p>${doctorName}</p>
      ${specialization ? `<span>${specialization}</span>` : ''}
    </div>
  </div>

  <table>
    <thead>
      <tr><th>Description</th><th class="amt">Amount</th></tr>
    </thead>
    <tbody>
      <tr><td>${description}</td><td class="amt">${amount}</td></tr>
    </tbody>
  </table>

  <div class="total">
    <div class="total-box">
      <div class="total-row"><span>Subtotal</span><span>${amount}</span></div>
      <div class="total-row grand"><span>Total</span><span>${amount}</span></div>
    </div>
  </div>

  <div class="foot">Thank you. Generated by the Telehealth portal.</div>
</body>
</html>`;
}

/**
 * Open a printable invoice in a new window and trigger the print / save-as-PDF dialog.
 */
export function downloadInvoice(invoice: Invoice): void {
    const html = buildInvoiceHtml(invoice);
    const win = window.open('', '_blank');
    if (!win) {
        // Popup blocked — fall back to an HTML file download.
        const blob = new Blob([html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `invoice-${invoice.id.slice(0, 8)}.html`;
        a.click();
        URL.revokeObjectURL(url);
        return;
    }
    win.document.open();
    win.document.write(html);
    win.document.close();
    win.focus();
    // Give the browser a tick to render before invoking print.
    win.setTimeout(() => win.print(), 300);
}
